//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemStoneLive_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class demandRequest
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string StoneName { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Shape { get; set; }
        public string Dimension { get; set; }
        public string Pieces { get; set; }
    }
}
