//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemStoneLive_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class perItemDetail
    {
        public int id { get; set; }
        public string userNames { get; set; }
        public string preSemi { get; set; }
        public string pType { get; set; }
        public string sName { get; set; }
        public string stoneSize { get; set; }
        public string sWeight { get; set; }
        public string sPieces { get; set; }
        public string sDimensions { get; set; }
        public string sColor { get; set; }
        public string sQuality { get; set; }
        public string stoneShape { get; set; }
        public string sOrigin { get; set; }
        public string sRemark { get; set; }
        public string scerAgency { get; set; }
        public string sCarat { get; set; }
        public string stockId { get; set; }
        public string sSupplierRef { get; set; }
        public string sPurchase { get; set; }
        public byte[] image1 { get; set; }
        public byte[] image2 { get; set; }
        public byte[] image3 { get; set; }
        public byte[] image4 { get; set; }
        public byte[] image5 { get; set; }
        public string bbPrice { get; set; }
        public string maxbbPrice { get; set; }
        public string vipPrice { get; set; }
        public string retailPrice { get; set; }
    }
}
